spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: '01609115380459f99ce09d4f4f34f6506002f8a00f44ba6e17ed7f18feadddf4'